name: CodKillstreaksPlugin
main: me.scott.codkillstreaksplugin.CodKillstreaksPlugin
version: 1.0
api-version: 1.16
author: NotTooShabby
description: A Call of Duty-style killstreaks plugin for Minecraft.


commands:
  codhelp:
    description: Tutorial on the purpose and how this plugin works.
    usage: /codhelp

